name: mam_sport_sante_app
description: MAM sport sante app
version: 1.0.0+1
publish_to: none

environment:
  sdk: "^3.3.0"

dependencies:

  flutter:
    sdk: flutter
  flutter_gen_runner: ^5.5.0+1
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  google_fonts: ^6.2.1
  intl: ^0.18.1
  riverpod_annotation: ^2.3.5

dev_dependencies:
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/laptop.jpg
    - assets/images/logo.jpg
    - assets/images/reunion.jpg
    - assets/images/afterwork.jpg
    - assets/images/taking-notes.jpg